version: '2'
services:
  app:
    image: corporaterewards/spotify_helper:latest
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sleep infinity
    # command: >
      # sh -c 'bundle && 
      # rake tmp:clear tmp:pids:clear tmp:create && 
      # bundle exec rails server --bind 0.0.0.0'
