default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: <%= ENV['SPOTIFY_HELPER_DATABASE_HOST'] %>
  username: <%= ENV['SPOTIFY_HELPER_DATABASE_USER'] %>
  password: <%= ENV['SPOTIFY_HELPER_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: spotify_helper_development

test:
  <<: *default
  database: spotify_helper_test

production:
  <<: *default
  database: spotify_helper_production


