default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: tune_up_development

test:
  <<: *default
  database: tune_up_test

staging:
  <<: *default
  database: <%= ENV['DB_NAME'] %>

production:
  adapter: mysql2
  pool: 5
  timeout: 5000
  database: "spotify_helper"
  url: <%= ENV['CLEARDB_DATABASE_URL'] %>
