# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

phrases = BannedPhrases.create(
    [
        { phrase: "admin" }, { phrase: "god" }, { phrase: "omnipotent" }, { phrase: "omniscient" }, { phrase: "nazi" }, { phrase: "hitler" }, { phrase: "abbo" }, { phrase: "abo" }, { phrase: "abortion" }, 
        { phrase: "abuse" }, { phrase: "addict" }, { phrase: "addicts" }, { phrase: "adult" }, { phrase: "africa" }, { phrase: "african" }, { phrase: "alla" }, { phrase: "allah" }, { phrase: "alligatorbait" }, 
        { phrase: "amateur" }, { phrase: "american" }, { phrase: "anal" }, { phrase: "analannie" }, { phrase: "analsex" }, { phrase: "angie" }, { phrase: "angry" }, { phrase: "anus" }, { phrase: "arab" }, 
        { phrase: "arabs" }, { phrase: "areola" }, { phrase: "argie" }, { phrase: "aroused" }, { phrase: "arse" }, { phrase: "arsehole" }, { phrase: "asian" }, { phrase: "ass" }, { phrase: "assassin" }, 
        { phrase: "assassinate" }, { phrase: "assassination" }, { phrase: "assault" }, { phrase: "assbagger" }, { phrase: "assblaster" }, { phrase: "assclown" }, { phrase: "asscowboy" }, { phrase: "asses" }, 
        { phrase: "assfuck" }, { phrase: "assfucker" }, { phrase: "asshat" }, { phrase: "asshole" }, { phrase: "assholes" }, { phrase: "asshore" }, { phrase: "assjockey" }, { phrase: "asskiss" }, 
        { phrase: "asskisser" }, { phrase: "assklown" }, { phrase: "asslick" }, { phrase: "asslicker" }, { phrase: "asslover" }, { phrase: "assman" }, { phrase: "assmonkey" }, { phrase: "assmunch" }, 
        { phrase: "assmuncher" }, { phrase: "asspacker" }, { phrase: "asspirate" }, { phrase: "asspuppies" }, { phrase: "assranger" }, { phrase: "asswhore" }, { phrase: "asswipe" }, { phrase: "athletesfoot" }, 
        { phrase: "attack" }, { phrase: "australian" }, { phrase: "babe" }, { phrase: "babies" }, { phrase: "backdoor" }, { phrase: "backdoorman" }, { phrase: "backseat" }, { phrase: "badfuck" }, 
        { phrase: "balllicker" }, { phrase: "balls" }, { phrase: "ballsack" }, { phrase: "banging" }, { phrase: "baptist" }, { phrase: "barelylegal" }, { phrase: "barf" }, { phrase: "barface" }, 
        { phrase: "barfface" }, { phrase: "bast" }, { phrase: "bastard" }, { phrase: "bazongas" }, { phrase: "bazooms" }, { phrase: "beaner" }, { phrase: "beast" }, { phrase: "beastality" }, 
        { phrase: "beastial" }, { phrase: "beastiality" }, { phrase: "beatoff" }, { phrase: "beat-off" }, { phrase: "beatyourmeat" }, { phrase: "beaver" }, { phrase: "bestial" }, { phrase: "bestiality" }, 
        { phrase: "bi" }, { phrase: "biatch" }, { phrase: "bible" }, { phrase: "bicurious" }, { phrase: "bigass" }, { phrase: "bigbastard" }, { phrase: "bigbutt" }, { phrase: "bigger" }, { phrase: "bisexual" }, 
        { phrase: "bi-sexual" }, { phrase: "bitch" }, { phrase: "bitcher" }, { phrase: "bitches" }, { phrase: "bitchez" }, { phrase: "bitchin" }, { phrase: "bitching" }, { phrase: "bitchslap" }, 
        { phrase: "bitchy" }, { phrase: "biteme" }, { phrase: "black" }, { phrase: "blackman" }, { phrase: "blackout" }, { phrase: "blacks" }, { phrase: "blind" }, { phrase: "blow" }, { phrase: "blowjob" }, 
        { phrase: "boang" }, { phrase: "bogan" }, { phrase: "bohunk" }, { phrase: "bollick" }, { phrase: "bollock" }, { phrase: "bomb" }, { phrase: "bombers" }, { phrase: "bombing" }, { phrase: "bombs" }, 
        { phrase: "bomd" }, { phrase: "bondage" }, { phrase: "boner" }, { phrase: "bong" }, { phrase: "boob" }, { phrase: "boobies" }, { phrase: "boobs" }, { phrase: "booby" }, { phrase: "boody" }, 
        { phrase: "boom" }, { phrase: "boong" }, { phrase: "boonga" }, { phrase: "boonie" }, { phrase: "booty" }, { phrase: "bootycall" }, { phrase: "bountybar" }, { phrase: "bra" }, { phrase: "brea5t" }, 
        { phrase: "breast" }, { phrase: "breastjob" }, { phrase: "breastlover" }, { phrase: "breastman" }, { phrase: "brothel" }, { phrase: "bugger" }, { phrase: "buggered" }, { phrase: "buggery" }, 
        { phrase: "bullcrap" }, { phrase: "bulldike" }, { phrase: "bulldyke" }, { phrase: "bullshit" }, { phrase: "bumblefuck" }, { phrase: "bumfuck" }, { phrase: "bunga" }, { phrase: "bunghole" }, 
        { phrase: "buried" }, { phrase: "burn" }, { phrase: "butchbabes" }, { phrase: "butchdike" }, { phrase: "butchdyke" }, { phrase: "butt" }, { phrase: "buttbang" }, { phrase: "butt-bang" }, 
        { phrase: "buttface" }, { phrase: "buttfuck" }, { phrase: "butt-fuck" }, { phrase: "buttfucker" }, { phrase: "butt-fucker" }, { phrase: "buttfuckers" }, { phrase: "butt-fuckers" }, 
        { phrase: "butthead" }, { phrase: "buttman" }, { phrase: "buttmunch" }, { phrase: "buttmuncher" }, { phrase: "buttpirate" }, { phrase: "buttplug" }, { phrase: "buttstain" }, { phrase: "byatch" }, 
        { phrase: "cacker" }, { phrase: "cameljockey" }, { phrase: "cameltoe" }, { phrase: "canadian" }, { phrase: "cancer" }, { phrase: "carpetmuncher" }, { phrase: "carruth" }, { phrase: "catholic" }, 
        { phrase: "catholics" }, { phrase: "cemetery" }, { phrase: "chav" }, { phrase: "cherrypopper" }, { phrase: "chickslick" }, { phrase: "chin" }, { phrase: "chinaman" }, { phrase: "chinamen" }, 
        { phrase: "chinese" }, { phrase: "chink" }, { phrase: "chinky" }, { phrase: "choad" }, { phrase: "chode" }, { phrase: "christ" }, { phrase: "christian" }, { phrase: "church" }, { phrase: "cigarette" }, 
        { phrase: "cigs" }, { phrase: "clamdigger" }, { phrase: "clamdiver" }, { phrase: "clit" }, { phrase: "clitoris" }, { phrase: "clogwog" }, { phrase: "cocaine" }, { phrase: "cock" }, 
        { phrase: "cockblock" }, { phrase: "cockblocker" }, { phrase: "cockcowboy" }, { phrase: "cockfight" }, { phrase: "cockhead" }, { phrase: "cockknob" }, { phrase: "cocklicker" }, { phrase: "cocklover" }, 
        { phrase: "cocknob" }, { phrase: "cockqueen" }, { phrase: "cockrider" }, { phrase: "cocksman" }, { phrase: "cocksmith" }, { phrase: "cocksmoker" }, { phrase: "cocksucer" }, { phrase: "cocksuck" }, 
        { phrase: "cocksucked" }, { phrase: "cocksucker" }, { phrase: "cocksucking" }, { phrase: "cocktail" }, { phrase: "cocktease" }, { phrase: "cocky" }, { phrase: "cohee" }, { phrase: "coitus" }, 
        { phrase: "color" }, { phrase: "colored" }, { phrase: "coloured" }, { phrase: "commie" }, { phrase: "communist" }, { phrase: "condom" }, { phrase: "conservative" }, { phrase: "conspiracy" }, 
        { phrase: "coolie" }, { phrase: "cooly" }, { phrase: "coon" }, { phrase: "coondog" }, { phrase: "copulate" }, { phrase: "cornhole" }, { phrase: "corruption" }, { phrase: "cra5h" }, { phrase: "crabs" }, 
        { phrase: "crack" }, { phrase: "crackpipe" }, { phrase: "crackwhore" }, { phrase: "crack-whore" }, { phrase: "crap" }, { phrase: "crapola" }, { phrase: "crapper" }, { phrase: "crappy" }, 
        { phrase: "crash" }, { phrase: "creamy" }, { phrase: "crime" }, { phrase: "crimes" }, { phrase: "criminal" }, { phrase: "criminals" }, { phrase: "crotch" }, { phrase: "crotchjockey" }, 
        { phrase: "crotchmonkey" }, { phrase: "crotchrot" }, { phrase: "cum" }, { phrase: "cumbubble" }, { phrase: "cumfest" }, { phrase: "cumjockey" }, { phrase: "cumm" }, { phrase: "cummer" }, 
        { phrase: "cumming" }, { phrase: "cumquat" }, { phrase: "cumqueen" }, { phrase: "cumshot" }, { phrase: "cunilingus" }, { phrase: "cunillingus" }, { phrase: "cunn" }, { phrase: "cunnilingus" }, 
        { phrase: "cunntt" }, { phrase: "cunt" }, { phrase: "cunteyed" }, { phrase: "cuntfuck" }, { phrase: "cuntfucker" }, { phrase: "cuntlick" }, { phrase: "cuntlicker" }, { phrase: "cuntlicking" }, 
        { phrase: "cuntsucker" }, { phrase: "cybersex" }, { phrase: "cyberslimer" }, { phrase: "dago" }, { phrase: "dahmer" }, { phrase: "dammit" }, { phrase: "damn" }, { phrase: "damnation" }, 
        { phrase: "damnit" }, { phrase: "darkie" }, { phrase: "darky" }, { phrase: "datnigga" }, { phrase: "dead" }, { phrase: "deapthroat" }, { phrase: "death" }, { phrase: "deepthroat" }, 
        { phrase: "defecate" }, { phrase: "dego" }, { phrase: "demon" }, { phrase: "deposit" }, { phrase: "desire" }, { phrase: "destroy" }, { phrase: "deth" }, { phrase: "devil" }, 
        { phrase: "devilworshipper" }, { phrase: "dick" }, { phrase: "dickbrain" }, { phrase: "dickforbrains" }, { phrase: "dickhead" }, { phrase: "dickless" }, { phrase: "dicklick" }, { phrase: "dicklicker" }, 
        { phrase: "dickman" }, { phrase: "dickwad" }, { phrase: "dickweed" }, { phrase: "diddle" }, { phrase: "die" }, { phrase: "died" }, { phrase: "dies" }, { phrase: "dike" }, { phrase: "dildo" }, 
        { phrase: "dingleberry" }, { phrase: "dink" }, { phrase: "dipshit" }, { phrase: "dipstick" }, { phrase: "dirty" }, { phrase: "disease" }, { phrase: "diseases" }, { phrase: "disturbed" }, 
        { phrase: "dive" }, { phrase: "dix" }, { phrase: "dixiedike" }, { phrase: "dixiedyke" }, { phrase: "doggiestyle" }, { phrase: "doggystyle" }, { phrase: "dong" }, { phrase: "doodoo" }, 
        { phrase: "doo-doo" }, { phrase: "doom" }, { phrase: "dope" }, { phrase: "dragqueen" }, { phrase: "dragqween" }, { phrase: "dripdick" }, { phrase: "drug" }, { phrase: "drunk" }, { phrase: "drunken" }, 
        { phrase: "dumb" }, { phrase: "dumbass" }, { phrase: "dumbbitch" }, { phrase: "dumbfuck" }, { phrase: "dyefly" }, { phrase: "dyke" }, { phrase: "easyslut" }, { phrase: "eatballs" }, { phrase: "eatme" }, 
        { phrase: "eatpussy" }, { phrase: "ecstacy" }, { phrase: "ejaculate" }, { phrase: "ejaculated" }, { phrase: "ejaculating" }, { phrase: "ejaculation" }, { phrase: "enema" }, { phrase: "enemy" }, 
        { phrase: "erect" }, { phrase: "erection" }, { phrase: "ero" }, { phrase: "escort" }, { phrase: "ethiopian" }, { phrase: "ethnic" }, { phrase: "european" }, { phrase: "evl" }, { phrase: "excrement" }, 
        { phrase: "execute" }, { phrase: "executed" }, { phrase: "execution" }, { phrase: "executioner" }, { phrase: "explosion" }, { phrase: "facefucker" }, { phrase: "faeces" }, { phrase: "fag" }, 
        { phrase: "fagging" }, { phrase: "faggot" }, { phrase: "fagot" }, { phrase: "failed" }, { phrase: "failure" }, { phrase: "fairies" }, { phrase: "fairy" }, { phrase: "faith" }, { phrase: "fannyfucker" }, 
        { phrase: "fart" }, { phrase: "farted" }, { phrase: "farting" }, { phrase: "farty" }, { phrase: "fastfuck" }, { phrase: "fat" }, { phrase: "fatah" }, { phrase: "fatass" }, { phrase: "fatfuck" }, 
        { phrase: "fatfucker" }, { phrase: "fatso" }, { phrase: "fckcum" }, { phrase: "fear" }, { phrase: "feces" }, { phrase: "felatio" }, { phrase: "felch" }, { phrase: "felcher" }, { phrase: "felching" }, 
        { phrase: "fellatio" }, { phrase: "feltch" }, { phrase: "feltcher" }, { phrase: "feltching" }, { phrase: "fetish" }, { phrase: "fight" }, { phrase: "filipina" }, { phrase: "filipino" }, 
        { phrase: "fingerfood" }, { phrase: "fingerfuck" }, { phrase: "fingerfucked" }, { phrase: "fingerfucker" }, { phrase: "fingerfuckers" }, { phrase: "fingerfucking" }, { phrase: "fire" }, 
        { phrase: "firing" }, { phrase: "fister" }, { phrase: "fistfuck" }, { phrase: "fistfucked" }, { phrase: "fistfucker" }, { phrase: "fistfucking" }, { phrase: "fisting" }, { phrase: "flange" }, 
        { phrase: "flasher" }, { phrase: "flatulence" }, { phrase: "floo" }, { phrase: "flydie" }, { phrase: "flydye" }, { phrase: "fok" }, { phrase: "fondle" }, { phrase: "footaction" }, { phrase: "footfuck" }, 
        { phrase: "footfucker" }, { phrase: "footlicker" }, { phrase: "footstar" }, { phrase: "fore" }, { phrase: "foreskin" }, { phrase: "forni" }, { phrase: "fornicate" }, { phrase: "foursome" }, 
        { phrase: "fourtwenty" }, { phrase: "fraud" }, { phrase: "freakfuck" }, { phrase: "freakyfucker" }, { phrase: "freefuck" }, { phrase: "fu" }, { phrase: "fubar" }, { phrase: "fuc" }, { phrase: "fucck" }, 
        { phrase: "fuck" }, { phrase: "fucka" }, { phrase: "fuckable" }, { phrase: "fuckbag" }, { phrase: "fuckbuddy" }, { phrase: "fucked" }, { phrase: "fuckedup" }, { phrase: "fucker" }, { phrase: "fuckers" }, 
        { phrase: "fuckface" }, { phrase: "fuckfest" }, { phrase: "fuckfreak" }, { phrase: "fuckfriend" }, { phrase: "fuckhead" }, { phrase: "fuckher" }, { phrase: "fuckin" }, { phrase: "fuckina" }, 
        { phrase: "fucking" }, { phrase: "fuckingbitch" }, { phrase: "fuckinnuts" }, { phrase: "fuckinright" }, { phrase: "fuckit" }, { phrase: "fuckknob" }, { phrase: "fuckme" }, { phrase: "fuckmehard" }, 
        { phrase: "fuckmonkey" }, { phrase: "fuckoff" }, { phrase: "fuckpig" }, { phrase: "fucks" }, { phrase: "fucktard" }, { phrase: "fuckwhore" }, { phrase: "fuckyou" }, { phrase: "fudgepacker" }, 
        { phrase: "fugly" }, { phrase: "fuk" }, { phrase: "fuks" }, { phrase: "funeral" }, { phrase: "funfuck" }, { phrase: "fungus" }, { phrase: "fuuck" }, { phrase: "gangbang" }, { phrase: "gangbanged" }, 
        { phrase: "gangbanger" }, { phrase: "gangsta" }, { phrase: "gatorbait" }, { phrase: "gay" }, { phrase: "gaymuthafuckinwhore" }, { phrase: "gaysex" }, { phrase: "geez" }, { phrase: "geezer" }, 
        { phrase: "geni" }, { phrase: "genital" }, { phrase: "german" }, { phrase: "getiton" }, { phrase: "gin" }, { phrase: "ginzo" }, { phrase: "gipp" }, { phrase: "girls" }, { phrase: "givehead" }, 
        { phrase: "glazeddonut" }, { phrase: "gob" }, { phrase: "god" }, { phrase: "godammit" }, { phrase: "goddamit" }, { phrase: "goddammit" }, { phrase: "goddamn" }, { phrase: "goddamned" }, 
        { phrase: "goddamnes" }, { phrase: "goddamnit" }, { phrase: "goddamnmuthafucker" }, { phrase: "goldenshower" }, { phrase: "gonorrehea" }, { phrase: "gonzagas" }, { phrase: "gook" }, 
        { phrase: "gotohell" }, { phrase: "goy" }, { phrase: "goyim" }, { phrase: "greaseball" }, { phrase: "gringo" }, { phrase: "groe" }, { phrase: "gross" }, { phrase: "grostulation" }, { phrase: "gubba" }, 
        { phrase: "gummer" }, { phrase: "gun" }, { phrase: "gyp" }, { phrase: "gypo" }, { phrase: "gypp" }, { phrase: "gyppie" }, { phrase: "gyppo" }, { phrase: "gyppy" }, { phrase: "hamas" }, 
        { phrase: "handjob" }, { phrase: "hapa" }, { phrase: "harder" }, { phrase: "hardon" }, { phrase: "harem" }, { phrase: "headfuck" }, { phrase: "headlights" }, { phrase: "hebe" }, { phrase: "heeb" }, 
        { phrase: "hell" }, { phrase: "henhouse" }, { phrase: "heroin" }, { phrase: "herpes" }, { phrase: "heterosexual" }, { phrase: "hijack" }, { phrase: "hijacker" }, { phrase: "hijacking" }, 
        { phrase: "hillbillies" }, { phrase: "hindoo" }, { phrase: "hiscock" }, { phrase: "hitler" }, { phrase: "hitlerism" }, { phrase: "hitlerist" }, { phrase: "hiv" }, { phrase: "ho" }, { phrase: "hobo" }, 
        { phrase: "hodgie" }, { phrase: "hoes" }, { phrase: "hole" }, { phrase: "holestuffer" }, { phrase: "homicide" }, { phrase: "homo" }, { phrase: "homobangers" }, { phrase: "homosexual" }, 
        { phrase: "honger" }, { phrase: "honk" }, { phrase: "honkers" }, { phrase: "honkey" }, { phrase: "honky" }, { phrase: "hook" }, { phrase: "hooker" }, { phrase: "hookers" }, { phrase: "hooters" }, 
        { phrase: "hore" }, { phrase: "hork" }, { phrase: "horn" }, { phrase: "horney" }, { phrase: "horniest" }, { phrase: "horny" }, { phrase: "horseshit" }, { phrase: "hosejob" }, { phrase: "hoser" }, 
        { phrase: "hostage" }, { phrase: "hotdamn" }, { phrase: "hotpussy" }, { phrase: "hottotrot" }, { phrase: "hummer" }, { phrase: "husky" }, { phrase: "hussy" }, { phrase: "hustler" }, { phrase: "hymen" }, 
        { phrase: "hymie" }, { phrase: "iblowu" }, { phrase: "idiot" }, { phrase: "ikey" }, { phrase: "illegal" }, { phrase: "incest" }, { phrase: "insest" }, { phrase: "intercourse" }, 
        { phrase: "interracial" }, { phrase: "intheass" }, { phrase: "inthebuff" }, { phrase: "israel" }, { phrase: "israeli" }, { phrase: "israel's" }, { phrase: "italiano" }, { phrase: "itch" }, 
        { phrase: "jackass" }, { phrase: "jackoff" }, { phrase: "jackshit" }, { phrase: "jacktheripper" }, { phrase: "jade" }, { phrase: "jap" }, { phrase: "japanese" }, { phrase: "japcrap" }, 
        { phrase: "jebus" }, { phrase: "jeez" }, { phrase: "jerkoff" }, { phrase: "jesus" }, { phrase: "jesuschrist" }, { phrase: "jew" }, { phrase: "jewish" }, { phrase: "jiga" }, { phrase: "jigaboo" }, 
        { phrase: "jigg" }, { phrase: "jigga" }, { phrase: "jiggabo" }, { phrase: "jigger" }, { phrase: "jiggy" }, { phrase: "jihad" }, { phrase: "jijjiboo" }, { phrase: "jimfish" }, { phrase: "jism" }, 
        { phrase: "jiz" }, { phrase: "jizim" }, { phrase: "jizjuice" }, { phrase: "jizm" }, { phrase: "jizz" }, { phrase: "jizzim" }, { phrase: "jizzum" }, { phrase: "joint" }, { phrase: "juggalo" }, 
        { phrase: "jugs" }, { phrase: "junglebunny" }, { phrase: "kaffer" }, { phrase: "kaffir" }, { phrase: "kaffre" }, { phrase: "kafir" }, { phrase: "kanake" }, { phrase: "kid" }, { phrase: "kigger" }, 
        { phrase: "kike" }, { phrase: "kill" }, { phrase: "killed" }, { phrase: "killer" }, { phrase: "killing" }, { phrase: "kills" }, { phrase: "kink" }, { phrase: "kinky" }, { phrase: "kissass" }, 
        { phrase: "kkk" }, { phrase: "knife" }, { phrase: "knockers" }, { phrase: "kock" }, { phrase: "kondum" }, { phrase: "koon" }, { phrase: "kotex" }, { phrase: "krap" }, { phrase: "krappy" }, 
        { phrase: "kraut" }, { phrase: "kum" }, { phrase: "kumbubble" }, { phrase: "kumbullbe" }, { phrase: "kummer" }, { phrase: "kumming" }, { phrase: "kumquat" }, { phrase: "kums" }, { phrase: "kunilingus" }, 
        { phrase: "kunnilingus" }, { phrase: "kunt" }, { phrase: "ky" }, { phrase: "kyke" }, { phrase: "lactate" }, { phrase: "laid" }, { phrase: "lapdance" }, { phrase: "latin" }, { phrase: "lesbain" }, 
        { phrase: "lesbayn" }, { phrase: "lesbian" }, { phrase: "lesbin" }, { phrase: "lesbo" }, { phrase: "lez" }, { phrase: "lezbe" }, { phrase: "lezbefriends" }, { phrase: "lezbo" }, { phrase: "lezz" }, 
        { phrase: "lezzo" }, { phrase: "liberal" }, { phrase: "libido" }, { phrase: "licker" }, { phrase: "lickme" }, { phrase: "lies" }, { phrase: "limey" }, { phrase: "limpdick" }, { phrase: "limy" }, 
        { phrase: "lingerie" }, { phrase: "liquor" }, { phrase: "livesex" }, { phrase: "loadedgun" }, { phrase: "lolita" }, { phrase: "looser" }, { phrase: "loser" }, { phrase: "lotion" }, 
        { phrase: "lovebone" }, { phrase: "lovegoo" }, { phrase: "lovegun" }, { phrase: "lovejuice" }, { phrase: "lovemuscle" }, { phrase: "lovepistol" }, { phrase: "loverocket" }, { phrase: "lowlife" }, 
        { phrase: "lsd" }, { phrase: "lubejob" }, { phrase: "lucifer" }, { phrase: "luckycammeltoe" }, { phrase: "lugan" }, { phrase: "lynch" }, { phrase: "macaca" }, { phrase: "mad" }, { phrase: "mafia" }, 
        { phrase: "magicwand" }, { phrase: "mams" }, { phrase: "manhater" }, { phrase: "manpaste" }, { phrase: "marijuana" }, { phrase: "mastabate" }, { phrase: "mastabater" }, { phrase: "masterbate" }, 
        { phrase: "masterblaster" }, { phrase: "mastrabator" }, { phrase: "masturbate" }, { phrase: "masturbating" }, { phrase: "mattressprincess" }, { phrase: "meatbeatter" }, { phrase: "meatrack" }, 
        { phrase: "meth" }, { phrase: "mexican" }, { phrase: "mgger" }, { phrase: "mggor" }, { phrase: "mickeyfinn" }, { phrase: "mideast" }, { phrase: "milf" }, { phrase: "minority" }, { phrase: "mockey" }, 
        { phrase: "mockie" }, { phrase: "mocky" }, { phrase: "mofo" }, { phrase: "moky" }, { phrase: "moles" }, { phrase: "molest" }, { phrase: "molestation" }, { phrase: "molester" }, { phrase: "molestor" }, 
        { phrase: "moneyshot" }, { phrase: "mooncricket" }, { phrase: "mormon" }, { phrase: "moron" }, { phrase: "moslem" }, { phrase: "mosshead" }, { phrase: "mothafuck" }, { phrase: "mothafucka" }, 
        { phrase: "mothafuckaz" }, { phrase: "mothafucked" }, { phrase: "mothafucker" }, { phrase: "mothafuckin" }, { phrase: "mothafucking" }, { phrase: "mothafuckings" }, { phrase: "motherfuck" }, 
        { phrase: "motherfucked" }, { phrase: "motherfucker" }, { phrase: "motherfuckin" }, { phrase: "motherfucking" }, { phrase: "motherfuckings" }, { phrase: "motherlovebone" }, { phrase: "muff" }, 
        { phrase: "muffdive" }, { phrase: "muffdiver" }, { phrase: "muffindiver" }, { phrase: "mufflikcer" }, { phrase: "mulatto" }, { phrase: "muncher" }, { phrase: "munt" }, { phrase: "murder" }, 
        { phrase: "murderer" }, { phrase: "muslim" }, { phrase: "naked" }, { phrase: "narcotic" }, { phrase: "nasty" }, { phrase: "nastybitch" }, { phrase: "nastyho" }, { phrase: "nastyslut" }, 
        { phrase: "nastywhore" }, { phrase: "nazi" }, { phrase: "necro" }, { phrase: "negro" }, { phrase: "negroes" }, { phrase: "negroid" }, { phrase: "negro's" }, { phrase: "nig" }, { phrase: "niger" }, 
        { phrase: "nigerian" }, { phrase: "nigerians" }, { phrase: "nigg" }, { phrase: "nigga" }, { phrase: "niggah" }, { phrase: "niggaracci" }, { phrase: "niggard" }, { phrase: "niggarded" }, 
        { phrase: "niggarding" }, { phrase: "niggardliness" }, { phrase: "niggardliness's" }, { phrase: "niggardly" }, { phrase: "niggards" }, { phrase: "niggard's" }, { phrase: "niggaz" }, { phrase: "nigger" }, 
        { phrase: "niggerhead" }, { phrase: "niggerhole" }, { phrase: "niggers" }, { phrase: "nigger's" }, { phrase: "niggle" }, { phrase: "niggled" }, { phrase: "niggles" }, { phrase: "niggling" }, 
        { phrase: "nigglings" }, { phrase: "niggor" }, { phrase: "niggur" }, { phrase: "niglet" }, { phrase: "nignog" }, { phrase: "nigr" }, { phrase: "nigra" }, { phrase: "nigre" }, { phrase: "nip" }, 
        { phrase: "nipple" }, { phrase: "nipplering" }, { phrase: "nittit" }, { phrase: "nlgger" }, { phrase: "nlggor" }, { phrase: "nofuckingway" }, { phrase: "nook" }, { phrase: "nookey" }, 
        { phrase: "nookie" }, { phrase: "noonan" }, { phrase: "nooner" }, { phrase: "nude" }, { phrase: "nudger" }, { phrase: "nuke" }, { phrase: "nutfucker" }, { phrase: "nymph" }, { phrase: "ontherag" }, 
        { phrase: "oral" }, { phrase: "orga" }, { phrase: "orgasim" }, { phrase: "orgasm" }, { phrase: "orgies" }, { phrase: "orgy" }, { phrase: "osama" }, { phrase: "paki" }, { phrase: "palesimian" }, 
        { phrase: "palestinian" }, { phrase: "pansies" }, { phrase: "pansy" }, { phrase: "panti" }, { phrase: "panties" }, { phrase: "payo" }, { phrase: "pearlnecklace" }, { phrase: "peck" }, 
        { phrase: "pecker" }, { phrase: "peckerwood" }, { phrase: "pee" }, { phrase: "peehole" }, { phrase: "pee-pee" }, { phrase: "peepshow" }, { phrase: "peepshpw" }, { phrase: "pendy" }, 
        { phrase: "penetration" }, { phrase: "peni5" }, { phrase: "penile" }, { phrase: "penis" }, { phrase: "penises" }, { phrase: "penthouse" }, { phrase: "period" }, { phrase: "perv" }, 
        { phrase: "phonesex" }, { phrase: "phuk" }, { phrase: "phuked" }, { phrase: "phuking" }, { phrase: "phukked" }, { phrase: "phukking" }, { phrase: "phungky" }, { phrase: "phuq" }, { phrase: "pi55" }, 
        { phrase: "picaninny" }, { phrase: "piccaninny" }, { phrase: "pickaninny" }, { phrase: "piker" }, { phrase: "pikey" }, { phrase: "piky" }, { phrase: "pimp" }, { phrase: "pimped" }, { phrase: "pimper" }, 
        { phrase: "pimpjuic" }, { phrase: "pimpjuice" }, { phrase: "pimpsimp" }, { phrase: "pindick" }, { phrase: "piss" }, { phrase: "pissed" }, { phrase: "pisser" }, { phrase: "pisses" }, 
        { phrase: "pisshead" }, { phrase: "pissin" }, { phrase: "pissing" }, { phrase: "pissoff" }, { phrase: "pistol" }, { phrase: "pixie" }, { phrase: "pixy" }, { phrase: "playboy" }, { phrase: "playgirl" }, 
        { phrase: "pocha" }, { phrase: "pocho" }, { phrase: "pocketpool" }, { phrase: "pohm" }, { phrase: "polack" }, { phrase: "pom" }, { phrase: "pommie" }, { phrase: "pommy" }, { phrase: "poo" }, 
        { phrase: "poon" }, { phrase: "poontang" }, { phrase: "poop" }, { phrase: "pooper" }, { phrase: "pooperscooper" }, { phrase: "pooping" }, { phrase: "poorwhitetrash" }, { phrase: "popimp" }, 
        { phrase: "porchmonkey" }, { phrase: "porn" }, { phrase: "pornflick" }, { phrase: "pornking" }, { phrase: "porno" }, { phrase: "pornography" }, { phrase: "pornprincess" }, { phrase: "pot" }, 
        { phrase: "poverty" }, { phrase: "premature" }, { phrase: "pric" }, { phrase: "prick" }, { phrase: "prickhead" }, { phrase: "primetime" }, { phrase: "propaganda" }, { phrase: "pros" }, 
        { phrase: "prostitute" }, { phrase: "protestant" }, { phrase: "pu55i" }, { phrase: "pu55y" }, { phrase: "pube" }, { phrase: "pubic" }, { phrase: "pubiclice" }, { phrase: "pud" }, { phrase: "pudboy" }, 
        { phrase: "pudd" }, { phrase: "puddboy" }, { phrase: "puke" }, { phrase: "puntang" }, { phrase: "purinapricness" }, { phrase: "puss" }, { phrase: "pussie" }, { phrase: "pussies" }, { phrase: "pussy" }, 
        { phrase: "pussycat" }, { phrase: "pussyeater" }, { phrase: "pussyfucker" }, { phrase: "pussylicker" }, { phrase: "pussylips" }, { phrase: "pussylover" }, { phrase: "pussypounder" }, { phrase: "pusy" }, 
        { phrase: "quashie" }, { phrase: "queef" }, { phrase: "queer" }, { phrase: "quickie" }, { phrase: "quim" }, { phrase: "ra8s" }, { phrase: "rabbi" }, { phrase: "racial" }, { phrase: "racist" }, 
        { phrase: "radical" }, { phrase: "radicals" }, { phrase: "raghead" }, { phrase: "randy" }, { phrase: "rape" }, { phrase: "raped" }, { phrase: "raper" }, { phrase: "rapist" }, { phrase: "rearend" }, 
        { phrase: "rearentry" }, { phrase: "rectum" }, { phrase: "redlight" }, { phrase: "redneck" }, { phrase: "reefer" }, { phrase: "reestie" }, { phrase: "refugee" }, { phrase: "reject" }, 
        { phrase: "remains" }, { phrase: "rentafuck" }, { phrase: "republican" }, { phrase: "rere" }, { phrase: "retard" }, { phrase: "retarded" }, { phrase: "ribbed" }, { phrase: "rigger" }, 
        { phrase: "rimjob" }, { phrase: "rimming" }, { phrase: "roach" }, { phrase: "robber" }, { phrase: "roundeye" }, { phrase: "rump" }, { phrase: "russki" }, { phrase: "russkie" }, { phrase: "sadis" }, 
        { phrase: "sadom" }, { phrase: "samckdaddy" }, { phrase: "sandm" }, { phrase: "sandnigger" }, { phrase: "satan" }, { phrase: "scag" }, { phrase: "scallywag" }, { phrase: "scat" }, { phrase: "schlong" }, 
        { phrase: "screw" }, { phrase: "screwyou" }, { phrase: "scrotum" }, { phrase: "scum" }, { phrase: "semen" }, { phrase: "seppo" }, { phrase: "servant" }, { phrase: "sex" }, { phrase: "sexed" }, 
        { phrase: "sexfarm" }, { phrase: "sexhound" }, { phrase: "sexhouse" }, { phrase: "sexing" }, { phrase: "sexkitten" }, { phrase: "sexpot" }, { phrase: "sexslave" }, { phrase: "sextogo" }, 
        { phrase: "sextoy" }, { phrase: "sextoys" }, { phrase: "sexual" }, { phrase: "sexually" }, { phrase: "sexwhore" }, { phrase: "sexy" }, { phrase: "sexymoma" }, { phrase: "sexy-slim" }, { phrase: "shag" }, 
        { phrase: "shaggin" }, { phrase: "shagging" }, { phrase: "shat" }, { phrase: "shav" }, { phrase: "shawtypimp" }, { phrase: "sheeney" }, { phrase: "shhit" }, { phrase: "shinola" }, { phrase: "shit" }, 
        { phrase: "shitcan" }, { phrase: "shitdick" }, { phrase: "shite" }, { phrase: "shiteater" }, { phrase: "shited" }, { phrase: "shitface" }, { phrase: "shitfaced" }, { phrase: "shitfit" }, 
        { phrase: "shitforbrains" }, { phrase: "shitfuck" }, { phrase: "shitfucker" }, { phrase: "shitfull" }, { phrase: "shithapens" }, { phrase: "shithappens" }, { phrase: "shithead" }, 
        { phrase: "shithouse" }, { phrase: "shiting" }, { phrase: "shitlist" }, { phrase: "shitola" }, { phrase: "shitoutofluck" }, { phrase: "shits" }, { phrase: "shitstain" }, { phrase: "shitted" }, 
        { phrase: "shitter" }, { phrase: "shitting" }, { phrase: "shitty" }, { phrase: "shoot" }, { phrase: "shooting" }, { phrase: "shortfuck" }, { phrase: "showtime" }, { phrase: "sick" }, { phrase: "sissy" }, 
        { phrase: "sixsixsix" }, { phrase: "sixtynine" }, { phrase: "sixtyniner" }, { phrase: "skank" }, { phrase: "skankbitch" }, { phrase: "skankfuck" }, { phrase: "skankwhore" }, { phrase: "skanky" }, 
        { phrase: "skankybitch" }, { phrase: "skankywhore" }, { phrase: "skinflute" }, { phrase: "skum" }, { phrase: "skumbag" }, { phrase: "slant" }, { phrase: "slanteye" }, { phrase: "slapper" }, 
        { phrase: "slaughter" }, { phrase: "slav" }, { phrase: "slave" }, { phrase: "slavedriver" }, { phrase: "sleezebag" }, { phrase: "sleezeball" }, { phrase: "slideitin" }, { phrase: "slime" }, 
        { phrase: "slimeball" }, { phrase: "slimebucket" }, { phrase: "slopehead" }, { phrase: "slopey" }, { phrase: "slopy" }, { phrase: "slut" }, { phrase: "sluts" }, { phrase: "slutt" }, 
        { phrase: "slutting" }, { phrase: "slutty" }, { phrase: "slutwear" }, { phrase: "slutwhore" }, { phrase: "smack" }, { phrase: "smackthemonkey" }, { phrase: "smut" }, { phrase: "snatch" }, 
        { phrase: "snatchpatch" }, { phrase: "snigger" }, { phrase: "sniggered" }, { phrase: "sniggering" }, { phrase: "sniggers" }, { phrase: "snigger's" }, { phrase: "sniper" }, { phrase: "snot" }, 
        { phrase: "snowback" }, { phrase: "snownigger" }, { phrase: "sob" }, { phrase: "sodom" }, { phrase: "sodomise" }, { phrase: "sodomite" }, { phrase: "sodomize" }, { phrase: "sodomy" }, 
        { phrase: "sonofabitch" }, { phrase: "sonofbitch" }, { phrase: "sooty" }, { phrase: "sos" }, { phrase: "soviet" }, { phrase: "spaghettibender" }, { phrase: "spaghettinigger" }, { phrase: "spank" }, 
        { phrase: "spankthemonkey" }, { phrase: "sperm" }, { phrase: "spermacide" }, { phrase: "spermbag" }, { phrase: "spermhearder" }, { phrase: "spermherder" }, { phrase: "spic" }, { phrase: "spick" }, 
        { phrase: "spig" }, { phrase: "spigotty" }, { phrase: "spik" }, { phrase: "spit" }, { phrase: "spitter" }, { phrase: "splittail" }, { phrase: "spooge" }, { phrase: "spreadeagle" }, { phrase: "spunk" }, 
        { phrase: "spunky" }, { phrase: "squaw" }, { phrase: "stagg" }, { phrase: "stiffy" }, { phrase: "strapon" }, { phrase: "stringer" }, { phrase: "stripclub" }, { phrase: "stroke" }, { phrase: "stroking" }, 
        { phrase: "stupid" }, { phrase: "stupidfuck" }, { phrase: "stupidfucker" }, { phrase: "suck" }, { phrase: "suckdick" }, { phrase: "sucker" }, { phrase: "suckme" }, { phrase: "suckmyass" }, 
        { phrase: "suckmydick" }, { phrase: "suckmytit" }, { phrase: "suckoff" }, { phrase: "suicide" }, { phrase: "swallow" }, { phrase: "swallower" }, { phrase: "swalow" }, { phrase: "swastika" }, 
        { phrase: "sweetness" }, { phrase: "syphilis" }, { phrase: "taboo" }, { phrase: "taff" }, { phrase: "tampon" }, { phrase: "tang" }, { phrase: "tantra" }, { phrase: "tarbaby" }, { phrase: "tard" }, 
        { phrase: "teat" }, { phrase: "terror" }, { phrase: "terrorist" }, { phrase: "teste" }, { phrase: "testicle" }, { phrase: "testicles" }, { phrase: "thicklips" }, { phrase: "thirdeye" }, 
        { phrase: "thirdleg" }, { phrase: "threesome" }, { phrase: "threeway" }, { phrase: "timbernigger" }, { phrase: "tinkle" }, { phrase: "tit" }, { phrase: "titbitnipply" }, { phrase: "titfuck" }, 
        { phrase: "titfucker" }, { phrase: "titfuckin" }, { phrase: "titjob" }, { phrase: "titlicker" }, { phrase: "titlover" }, { phrase: "tits" }, { phrase: "tittie" }, { phrase: "titties" }, 
        { phrase: "titty" }, { phrase: "tnt" }, { phrase: "toilet" }, { phrase: "tongethruster" }, { phrase: "tongue" }, { phrase: "tonguethrust" }, { phrase: "tonguetramp" }, { phrase: "tortur" }, 
        { phrase: "torture" }, { phrase: "tosser" }, { phrase: "towelhead" }, { phrase: "trailertrash" }, { phrase: "tramp" }, { phrase: "trannie" }, { phrase: "tranny" }, { phrase: "transexual" }, 
        { phrase: "transsexual" }, { phrase: "transvestite" }, { phrase: "triplex" }, { phrase: "trisexual" }, { phrase: "trojan" }, { phrase: "trots" }, { phrase: "tuckahoe" }, { phrase: "tunneloflove" }, 
        { phrase: "turd" }, { phrase: "turnon" }, { phrase: "twat" }, { phrase: "twink" }, { phrase: "twinkie" }, { phrase: "twobitwhore" }, { phrase: "uck" }, { phrase: "uk" }, { phrase: "unfuckable" }, 
        { phrase: "upskirt" }, { phrase: "uptheass" }, { phrase: "upthebutt" }, { phrase: "urinary" }, { phrase: "urinate" }, { phrase: "urine" }, { phrase: "usama" }, { phrase: "uterus" }, { phrase: "vagina" }, 
        { phrase: "vaginal" }, { phrase: "vatican" }, { phrase: "vibr" }, { phrase: "vibrater" }, { phrase: "vibrator" }, { phrase: "vietcong" }, { phrase: "violence" }, { phrase: "virgin" }, 
        { phrase: "virginbreaker" }, { phrase: "vomit" }, { phrase: "vulva" }, { phrase: "wab" }, { phrase: "wank" }, { phrase: "wanker" }, { phrase: "wanking" }, { phrase: "waysted" }, { phrase: "weapon" }, 
        { phrase: "weenie" }, { phrase: "weewee" }, { phrase: "welcher" }, { phrase: "welfare" }, { phrase: "wetb" }, { phrase: "wetback" }, { phrase: "wetspot" }, { phrase: "whacker" }, { phrase: "whash" }, 
        { phrase: "whigger" }, { phrase: "whiskey" }, { phrase: "whiskeydick" }, { phrase: "whiskydick" }, { phrase: "whit" }, { phrase: "whitenigger" }, { phrase: "whites" }, { phrase: "whitetrash" }, 
        { phrase: "whitey" }, { phrase: "whiz" }, { phrase: "whop" }, { phrase: "whore" }, { phrase: "whorefucker" }, { phrase: "whorehouse" }, { phrase: "wigger" }, { phrase: "willie" }, 
        { phrase: "williewanker" }, { phrase: "willy" }, { phrase: "wn" }, { phrase: "wog" }, { phrase: "wop" }, { phrase: "wtf" }, { phrase: "wuss" }, { phrase: "wuzzie" }, { phrase: "xtc" }, { phrase: "xxx" }, 
        { phrase: "yankee" }, { phrase: "yellowman" }, { phrase: "zigabo" }, { phrase: "zipperhead" }
    ]
)